spring:
  datasource:
    username: ${testDb.test.datasource.username}
    password: ${testDb.test.datasource.password}
    url: ${testDb.test.datasource.url}
  jpa:
    hibernate:
      ddl-auto: create-drop
