spring:
  datasource:
    url: ${db.dev.datasource.url}
    username: ${db.dev.datasource.username}
    password: ${db.dev.datasource.password}
  redis:
    host: localhost
    port: 6379

cloud:
  aws:
    credentials:
      access-key: ${aws.credentials.access-key}
      secret-key: ${aws.credentials.secret-key}
    s3:
      bucket: ${aws.s3.bucket}
    region:
      static: ${aws.region.static}
  stack:
    auto: false
