-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 22:42:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tomato_market
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tomato_market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tomato_market` DEFAULT CHARACTER SET utf8;
USE `tomato_market`;

-- -----------------------------------------------------
-- Table `tomato_market`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomato_market`.`member`
(
    `id`       BIGINT       NOT NULL AUTO_INCREMENT,
    `nickname` VARCHAR(45)  NOT NULL,
    `email`    VARCHAR(150) NOT NULL,
    `profile`  VARCHAR(256) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `login_id_UNIQUE` (`nickname` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tomato_market`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomato_market`.`category`
(
    `id`             BIGINT       NOT NULL AUTO_INCREMENT,
    `name`           VARCHAR(45)  NOT NULL,
    `category_image` VARCHAR(256) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tomato_market`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomato_market`.`item`
(
    `id`          BIGINT       NOT NULL AUTO_INCREMENT,
    `title`       VARCHAR(100) NOT NULL,
    `content`     LONGTEXT     NOT NULL,
    `price`       INT          NULL,
    `thumbnail`   VARCHAR(512) NOT NULL,
    `status`      VARCHAR(20)  NOT NULL,
    `region`      VARCHAR(100) NOT NULL,
    `chat_count`  BIGINT       NOT NULL,
    `wish_count`  BIGINT       NOT NULL,
    `view_count`  BIGINT       NOT NULL,
    `created_at`  TIMESTAMP    NOT NULL,
    `member_id`   BIGINT       NOT NULL,
    `category_id` BIGINT       NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tomato_market`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomato_market`.`region`
(
    `id`                BIGINT       NOT NULL AUTO_INCREMENT,
    `address_name`      VARCHAR(255) NOT NULL,
    `full_address_name` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tomato_market`.`memberTown`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomato_market`.`member_town`
(
    `id`          BIGINT       NOT NULL AUTO_INCREMENT,
    `member_id`   BIGINT       NOT NULL,
    `name`        VARCHAR(100) NOT NULL,
    `region_id`   BIGINT       NOT NULL,
    `is_selected` TINYINT      NOT NULL,
    PRIMARY KEY (`id`, `member_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tomato_market`.`wish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomato_market`.`wish`
(
    `id`        BIGINT NOT NULL AUTO_INCREMENT,
    `member_id` BIGINT NOT NULL,
    `item_id`   BIGINT NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tomato_market`.`chat_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomato_market`.`chat_log`
(
    `id`          BIGINT       NOT NULL AUTO_INCREMENT,
    `message`     VARCHAR(512) NOT NULL,
    `sender`      VARCHAR(45)  NOT NULL,
    `receiver`    VARCHAR(45)  NOT NULL,
    `created_at`  TIMESTAMP    NOT NULL,
    `new_massage` BIGINT       NOT NULL,
    `chatroom_id` BIGINT       NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tomato_market`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomato_market`.`image`
(
    `id`        BIGINT       NOT NULL AUTO_INCREMENT,
    `image_url` VARCHAR(512) NOT NULL,
    `item_id`   BIGINT       NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tomato_market`.`chatroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomato_market`.`chatroom`
(
    `id`         BIGINT    NOT NULL AUTO_INCREMENT,
    `created_at` TIMESTAMP NOT NULL,
    `seller_id`  BIGINT    NOT NULL,
    `buyer_id`   BIGINT    NOT NULL,
    `item_id`    BIGINT    NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
